characters = [
  // Mario
  { name: "Mario", image: "assets/characters/mario.webp" },
  { name: "Luigi", image: "assets/characters/luigi.webp" },
  { name: "Peach", image: "assets/characters/peach.webp" },
  { name: "Toad", image: "assets/characters/toad.webp" },
  { name: "Yoshi", image: "assets/characters/yoshi.webp" },
  { name: "Wario", image: "assets/characters/wario.webp" },
  { name: "Donkey Kong", image: "assets/characters/donkey_kong.webp" },
  { name: "Diddy Kong", image: "assets/characters/diddy_kong.webp" },
  // Pokemony
  { name: "Pikachu", image: "assets/characters/pikachu.webp" },
  { name: "Jigglypuff", image: "assets/characters/jigglypuff.webp" },
  { name: "Mewtwo", image: "assets/characters/mewtwo.webp" },
  { name: "Charmander", image: "assets/characters/charmander.webp" },
  { name: "Squirtle", image: "assets/characters/squirtle.webp" },
  { name: "Bulbasaur", image: "assets/characters/bulbasaur.webp" },
  { name: "Snorlax", image: "assets/characters/snorlax.webp" },
  // Sonic
  { name: "Sonic", image: "assets/characters/sonic.webp" },
  { name: "Tails", image: "assets/characters/tails.webp" },
  { name: "Knuckles", image: "assets/characters/knuckles.webp" },
  { name: "Shadow", image: "assets/characters/shadow.webp" },
  // Wiedźmin
  { name: "Geralt", image: "assets/characters/geralt.webp" },
  { name: "Triss", image: "assets/characters/triss.webp" },
  { name: "Yennefer", image: "assets/characters/yennefer.webp" },
  { name: "Ciri", image: "assets/characters/ciri.webp" },
  { name: "Zoltan", image: "assets/characters/zoltan.webp" },
  { name: "Eskel", image: "assets/characters/eskel.webp" },
  { name: "Lambert", image: "assets/characters/lambert.webp" },
  { name: "Dijkstra", image: "assets/characters/dijkstra.webp" },
  { name: "Eredin", image: "assets/characters/eredin.webp" },
  { name: "Priscilla", image: "assets/characters/priscilla.webp" },
  { name: "Jaskier", image: "assets/characters/jaskier.webp" },
  // Gta:
  { name: "Tommy", image: "assets/characters/tommy.webp" },
  { name: "CJ", image: "assets/characters/cj.webp" },
  { name: "Niko", image: "assets/characters/niko.webp" },
  { name: "Michael", image: "assets/characters/michael.webp" },
  { name: "Franklin", image: "assets/characters/franklin.webp" },
  { name: "Trevor", image: "assets/characters/trevor.webp" },
  { name: "Amanda", image: "assets/characters/amanda.webp" },
  { name: "Jimmy", image: "assets/characters/jimmy.webp" },
  { name: "Tracey", image: "assets/characters/tracey.webp" },
  { name: "Dave", image: "assets/characters/dave.webp" },
  { name: "Lamar", image: "assets/characters/lamar.webp" },
  { name: "Solomon", image: "assets/characters/solomon.webp" },
  { name: "Martin", image: "assets/characters/martin.webp" },
  { name: "Simeon", image: "assets/characters/simeon.webp" },
  // Minecraft
  { name: "Steve", image: "assets/characters/steve.webp" },
  { name: "Alex", image: "assets/characters/alex.webp" },
  { name: "Creeper", image: "assets/characters/creeper.webp" },
  { name: "Enderman", image: "assets/characters/enderman.webp" },
  { name: "Ghast", image: "assets/characters/ghast.webp" },
  { name: "Herobrine", image: "assets/characters/herobrine.webp" },
  // League of Legends
  { name: "Ahri", image: "assets/characters/ahri.webp" },
  { name: "Ezreal", image: "assets/characters/ezreal.webp" },
  { name: "Garen", image: "assets/characters/garen.webp" },
  { name: "Jinx", image: "assets/characters/jinx.webp" },
  { name: "Katarina", image: "assets/characters/katarina.webp" },
  { name: "Master Yi", image: "assets/characters/master_yi.webp" },
  { name: "Riven", image: "assets/characters/riven.webp" },
  { name: "Shen", image: "assets/characters/shen.webp" },
  { name: "Zed", image: "assets/characters/zed.webp" },
  { name: "Singed", image: "assets/characters/singed.webp" },
  { name: "Warwick", image: "assets/characters/warwick.webp" },
  { name: "Teemo", image: "assets/characters/teemo.webp" },
  // The Last of Us
  { name: "Joel", image: "assets/characters/joel.webp" },
  { name: "Ellie", image: "assets/characters/ellie.webp" },
  // God of War
  { name: "Kratos", image: "assets/characters/kratos.webp" },
];
